//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public int Identificacion { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Telefonos { get; set; }
        public string Correos { get; set; }
        public string Facebook { get; set; }
        public string Instagram { get; set; }
        public string Twitter { get; set; }
    
        public virtual Contacto Contacto1 { get; set; }
        public virtual Contacto Contacto2 { get; set; }
        public virtual CorreoElectronico CorreoElectronico { get; set; }
        public virtual Telefonos Telefonos1 { get; set; }
    }
}
